version: '3.8'

services:
  # Development environment
  andamios-orm-dev:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/workspace
      - poetry-cache:/root/.cache/pypoetry
      - pip-cache:/root/.cache/pip
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src
      - ANDAMIOS_ORM_ENV=development
      - ANDAMIOS_ORM_LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"  # For any web interfaces
    stdin_open: true
    tty: true
    command: /bin/bash
    depends_on:
      - duckdb-test

  # DuckDB test instance (for testing with file-based DB)
  duckdb-test:
    image: alpine:3.19
    volumes:
      - duckdb-data:/data
    command: |
      sh -c "
        apk add --no-cache python3 py3-pip &&
        pip3 install duckdb &&
        mkdir -p /data/test-databases &&
        tail -f /dev/null
      "
    environment:
      - DUCKDB_DATA_DIR=/data/test-databases

  # Testing environment for CI/CD
  andamios-orm-test:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
      target: test
    volumes:
      - .:/workspace
      - test-data:/workspace/test-data
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src
      - ANDAMIOS_ORM_ENV=testing
      - ANDAMIOS_ORM_LOG_LEVEL=WARNING
      - ANDAMIOS_ORM_TEST_DB_DIR=/workspace/test-data
    command: poetry run pytest
    depends_on:
      - duckdb-test

  # Documentation server
  docs:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
      target: docs
    volumes:
      - .:/workspace
      - docs-build:/workspace/docs/_build
    working_dir: /workspace
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/workspace/src
    command: |
      sh -c "
        cd docs &&
        poetry run sphinx-build -b html . _build/html &&
        poetry run python -m http.server 8080 --directory _build/html
      "

  # Performance testing environment
  performance:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
      target: performance
    volumes:
      - .:/workspace
      - benchmark-data:/workspace/benchmarks/data
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src
      - ANDAMIOS_ORM_ENV=performance
      - ANDAMIOS_ORM_LOG_LEVEL=ERROR
    command: poetry run pytest -m performance --benchmark-only
    depends_on:
      - duckdb-test

volumes:
  poetry-cache:
    driver: local
  pip-cache:
    driver: local
  duckdb-data:
    driver: local
  test-data:
    driver: local
  docs-build:
    driver: local
  benchmark-data:
    driver: local

networks:
  default:
    name: andamios-orm-network